urls.py
from django.conf.urls.defaults import patterns, include, url

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'yssite.views.home', name='home'),
    # url(r'^yssite/', include('yssite.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    url(r'^admin/', include(admin.site.urls)),
    url(r'^book/list/$','blog.list.index'),
    url(r'^index/reg/$','mem.views.index'),
)

blog/models.py
from django.db import models


# Create your models here.
sex_choices=(
    ('f','famale'),
    ('m','male'),
)

class Member(models.Model):
    name = models.CharField(max_length=30)
    sex  = models.CharField(max_length=1, choices=sex_choices)
    headImg = models.FileField(upload_to='/home/lmb/yssite/static/images/')

    def __unicode__(self):
        return self.name


class Author(models.Model):
    name = models.CharField(max_length=30)

    def __unicode__(self):
        return self.name

class Books(models.Model):
    name = models.CharField(max_length=30)
    authors = models.ManyToManyField(Author)
    bookImg = models.FileField(upload_to='/home/lmb/yssite/static/images/')

    def __unicode__(self):
        return self.name

mem/models.py
from django.db import models

# Create your models here.

blog/views.py
# Create your views here.

mem/views.py
from django import forms
from django.http import  HttpResponse
from django.shortcuts import render_to_response

class UserForm(forms.Form):
    name = forms.CharField()
    passwd = forms.CharField()
    headImg = forms.FileField()

def index(req):
    if req.method == 'POST':
        form = UserForm(req.POST,req.FILES)

        if form.is_valid():
            print form.cleaned_data
            fp = file('/home/lmb/yssite/upload/'+form.cleaned_data['headImg'].name,'wb')
            s = form.cleaned_data['headImg'].read()
            fp.write(s)
            fp.close()
            return HttpResponse('OK')

    else:
        form = UserForm()
    return  render_to_response('reg.html',{'form':form})

templates/list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link href="/static/css/index.css" type="text/css" rel="stylesheet">
</head>
<body>
<h1>测试</h1>
<div>
    {{books}}
</div>

{% for zuozhe in authors %}
<li class="author">{{zuozhe.name}}</li>

    {% for book in zuozhe.books_set.all %}
        <span class="book">&nbsp;&nbsp;&nbsp;{{book}}</span>
    {% endfor %}

{% endfor %}
<!--<img src="/static/123_6.jpg">-->
</body>
</html>

templates/reg.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>注册</title>
</head>
<body>
<form method="post" enctype="multipart/form-data">

    {{form}}

    <input type="submit" value="ok">

</form>
</body>
</html>